### ISSUE TITLE
JB returns output in a string when used with Rails 7.1

### ISSUE THREAD

**Issue by HunterHillegas** [amatsuda/jb#43]
It seems that using the gem in conjunction with Rails 7.1, the output is all wrapped in double quotes (i.e. a string) instead of returning correctly. This of course breaks most clients.

i.e. the raw response is `"{}"` instead of `{}`.

Content-Type is still correct: Content-Type: application/json; charset=utf-8

**Comment by hatsu38** [comment]
I have the same problem and am looking for a solution.

**Comment by amatsuda** [comment]
@HunterHillegas Thank you for reporting this issue! This issue was caused by an incompatible change in Action View via rails/rails@ee68644c284aa7512d06b4b5514b1236c1b63f55, and has been fixed via fb4b0de6c8b96b8b018cc623644a89a7b40faa96 which is included in version 0.8.1 gem release.

Please let me know if it still doesn't work for you.
